### ISSUE TITLE
Allow "skos:hasTopconcept" 

### ISSUE THREAD

**Issue by BaptisteCecconi** [ivoa-std/vocinvo#7]
In the frame of the FAIR-IMPACT project, we have implemented an OntoPortal instance (https://ontoportal.org), which is meant to aggregate vocabularies and ontologies from astronomy, heliophysics, or planetary sciences into a single place, so that we improve our semantic interoperability. 

In this tool, the processing of SKOS vocabularies requires to implement "skos:hasTopconcept" relations, in order to build the term hierarchy. This is an issue with IVOA-UAT specifically, (note that the original UAT is ingested with no issue in OntoPortal).

**Comment by msdemlei** [comment]
On Fri, Mar 01, 2024 at 04:47:55AM -0800, Baptiste Cecconi wrote:
> In this tool, the processing of SKOS vocabularies requires to
> implement "skos:hasTopconcept" relations, in order to build the

If external interoperability requires that, then we should have that,
yes.  We would have to change 4.1.1 then, which could go in in
version 1.2.  Do you have a reasonable explanatory text, i.e., a few
sentences explaining why we're doing that and, if applicable, what VO
clients are supposed to do with it?

Since I'm not quite sure about that latter question, I in particular
am not sure whether we should require the use of hasTopconcept.  It
wouldn't be hard to say something like "SKOS concepts with no
broader concepts must be objects in <vocabulary> skos:hasTopconcept
<concept> triples"; but do we want that?

**Comment by BaptisteCecconi** [comment]
Yes, this is essentially external interoperability (to my current knowledge). The current version of the IVOA-UAT doesn't have `skos:hasTopconcept`, and generic ontology tools have to guess what are top level concepts. 

The Ontoportal engine (based on [OWLAPI](https://github.com/owlcs/owlapi)) struggles to display SKOS vocabularies without top concepts, since it doesn't know where to start the hierarchy. 

There was another bug in IVOA-UAT (fixed in https://github.com/ivoa-std/Vocabularies/pull/20), but still, the Ontoportal engine only shows one tree (starting with `#astrophysical-processes`) but the other top level concepts are not there. Having top concept will allow to display top concepts and there respective trees properly.

**Comment by msdemlei** [comment]
Ok... over in Vocabularies there's now the PR 23 <https://github.com/ivoa-std/Vocabularies/pull/23> that ought to do the right thing, although I haven't studied SKOS quite enough to be sure.

I've alread updated the IVOA version of the UAT.

Suggestion: Let's see if the SKOS consumers are happy.  If they are, we should decide whether non-SKOS vocabularies should refuse topconcepts or whether they should just declare the SKOS prefix.  I *could* see a point in marking everything with a 1 in the second column of a terms.csv as a top concept regardless of whether we're really talking about skos:Concept-s (or rather RDFS classes or properties).  But I can just as well see that that's a horrible thing to do.

**Comment by BaptisteCecconi** [comment]
yes, let me try out the new UAT version and see how it goes.

**Comment by msdemlei** [comment]
Has https://github.com/ivoa-std/Vocabularies/pull/23 addressed this bug?
If you, could you close it so everything remains tidy?

**Comment by BaptisteCecconi** [comment]
yes, this is fixed now.
